apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: msa-db
  labels:
    app: msa-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-db
  serviceName: msa-db-headless
  template:
    metadata:
      labels:
        app: msa-db
    spec:
      containers:
      - name: mysql
        image: makersworld/msa-db-mysql8:amd64
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12341234"
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        hostPath:
          path: /data/mysql
          type: DirectoryOrCreate
#        volumeMounts:
#        - name: mysql-persistent-storage
#          mountPath: /var/lib/mysql
#  volumeClaimTemplates:
#    - metadata:
#        name: data
#      spec:
#        accessModes: ["ReadWriteOnce"]
#        storageClassName: gp3
#        resources:
#          requests:
#            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: msa-db-headless
  labels:
    app: msa-db
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None
  selector:
    app: msa-db
---
apiVersion: v1
kind: Service
metadata:
  name: msa-db-service
  labels:
    app: msa-db
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30303  # 외부에서 접근할 포트
  selector:
    app: msa-db