apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-basic-deployment
  name: msa-user
  labels:
    app: msa-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-user
  template:
    metadata:
      labels:
        app: msa-user
    spec:
      containers:
      - name: msa-user
        image: chadchae1373/msa_user:0.99
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "msa-db-service"  # MySQL 서비스 이름
        - name: DB_PORT
          value: "3306"          # MySQL 포트
        - name: DB_USER
          value: "root"            # MySQL 사용자 이름
        - name: DB_PASSWORD
          value: "12341234"        # MySQL 비밀번호
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-basic-deployment
  name: msa-user-service
  labels:
    app: msa-user
spec:
  type: LoadBalancer
  selector:
    app: msa-user
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080